export const GET_ALL_POKEMONS_START = "@pokemons/GET_ALL_POKEMONS_START"
export const GET_ALL_POKEMONS_SUCCESS = "@pokemons/GET_ALL_POKEMONS_SUCCESS"
export const GET_ALL_POKEMONS_FAILURE = "@pokemons/GET_ALL_POKEMONS_FAILURE"
