export const GET_SEARCH_POKEMON_START = "@pokemons/SEARCH_POKEMON_START"
export const GET_SEARCH_POKEMON_SUCCESS = "@pokemons/SEARCH_POKEMON_SUCCESS"
export const GET_SEARCH_POKEMON_FAILURE = "@pokemons/SEARCH_POKEMON_FAILURE"
export const DELETE_SEARCH_POKEMON_RESULT = "@pokemons/DELETE_SEARCH_POKEMON_RESULT"
